### ISSUE TITLE
对于获取iNode版本号方法的新思路

### ISSUE THREAD

**Issue by liuhuanan** [bitdust/dummy_H3C#2]
百度了一下替代iNode认证的第三方客户端，有两种都是通过上传iNode安装路径下的iNode.vif文件，来获得的版本号信息（可能还包含密匙信息等其它认证信息）。

**Comment by bitdust** [comment]
我也注意到了iNode.vif这个文件。
但是不知道如何使用~所以暂时没有什么办法。有没有什么开源项目可以解析这个东西了？

**Comment by liuhuanan** [comment]
开源的还真没找到，不过你对逆向工程很拿手，可以拿网上现成第三方客户端反汇编一下，看看他们从上传的iNode.vif文件中提取了什么信息，做了哪些处理

**Comment by bitdust** [comment]
哈~我的逆向工作纯粹是为了破解inode而学会的，也就是说。。。并不是很擅长。
不过这个寒假无聊的话，我会这么试试的。
