### ISSUE TITLE
关于auth.c中添加的SendFirstResponseIdentity函数在静态IP环境下存在的问题

### ISSUE THREAD

**Issue by liuhuanan** [bitdust/dummy_H3C#3]
发现无法再njit下添加评论。。。。
在静态IP网络环境下，由于SendFirstResponseIdentity函数没有包含上传IP地址，服务器会反馈IP绑定检查失败。不明白为何把上传ip的字段注释了呢？

另外请问 用本机MAC地址的后两位作为伪装IP地址是要实现什么功能？

**Comment by bitdust** [comment]
我们学校是在第一个ResponseIdentity包里没有上传IP地址。
因为我们的动态IP地址获取过程，即DHCP应该是在认证成功后进行的~而在认证成功之前，你的机器应该是没有IP地址的（起码没有一个合理的IP地址）。
根据我的经验，inode客户端的判断方式是：在获得合法IP后，就会在每一个ResponseIdentity包里携带IP地址~没有合法IP就不上传。而第一个ResponseIdentity包发送的时候，通常是没有IP地址的，所以我就没上传。
总之，上传IP地址与否，根据你的抓包实际情况考虑就好了。

出于简化代码的考虑，因为获取本机IP地址的代码，你自己看吧，写的蛮丑的，而且很难跨平台。所以我就索性不获取IP地址了，然而为了防止管理员在系统日志里看出异常（所有人都在用一个IP地址），所以我就用本机唯一的MAC码作为IP地址上传了~
我相信njit8021xclient这个项目的生命力在于它代码的简洁性，让大家更容易看懂它的代码。至于功能的完善，只要针对自己的网络环境做改写就可以了。既然你是静态IP地址，那么就添加个配置项就可以了。

**Comment by bitdust** [comment]
njit8021xclient的主分支在liuqun那里，所以我的这个fork里没有办法添加issue。
推荐你在我的NXSharp项目里提关于客户端的issue~
